server:
  port: ${SERVER_PORT:7001}

spring:
  application:
    name: users-service
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
    enabled: true
    service:
      name: users-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5


