server:
  port: ${SERVER_PORT}

info:
  component: Edge Server
spring:
  application:
    name: gateway-server
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
    enabled: true
    service:
      name: gateway-server
    message-timeout: 10
  sleuth:
      sampler:
        probability: 1.0
zuul:
  prefix: /api
  routes:
    address:
      path: /address/**
      serviceId: address-service
    users:
      path: /users/**
      serviceId: users-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    registerWithEureka: true
  instance:
    prefer-ip-address: false